name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Detect go version
        id: go-version
        run: echo "::set-output name=VERSION::$(cat .go-version)"
      - name: Setup go
        uses: actions/setup-go@master
        with:
          stable: 'false'
          go-version: ${{ steps.go-version.outputs.VERSION }}
      - name: Run test
        run: make test
        env:
          GOARGS: "-v -race"
          GOMAXPROCS: 8
      - name: Report coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./tmp/cover.out
      - name: Run demo
        run: make demo
